--3. 모든 교수는 교수번호를 부여하여 식별하며
-- 교수이름, 교수주소, 교수전화번호. 교수이메일, 소속 학과번호 정보를 가진다.

-- 교수
CREATE TABLE TB_PROFESSOR (
	PROF_NO NUMBER CONSTRAINT PROF_NO_PK PRIMARY KEY,
	PROF_NAME VARCHAR(30),
	PROF_ADDRESS VARCHAR(50),
	PROF_PHONE VARCHAR(20),
	PROF_EMAIL VARCHAR(50)
);


-- 강좌
CREATE TABLE TB_CLASS (
CLS_NO NUMBER PRIMARY KEY,
CLS_DIV_NO NUMBER,
CLS_NAME VARCHAR2(30),
CLS_DAY VARCHAR2(5),
CLS_TIME VARCHAR2(20),
CLS_SCORE NUMBER,
CLS_HOUR NUMBER,
DEPT_INFO VARCHAR2(30),
CLASSROOM VARCHAR2(30)
);

-- 학생
CREATE TABLE TB_STUDENT (
STD_NO NUMBER PRIMARY KEY,
STD_NAME VARCHAR2(30),
STD_ADDR VARCHAR2(45),
STD_PHONE VARCHAR2(20),
STD_EMAIL VARCHAR2(30),
STD_MAJOR VARCHAR2(30),
STD_MANOR VARCHAR2(30),
STD_PROF_INFO VARCHAR2(30),
STD_ACCOUND VARCHAR2(30)

);

-- 학과
CREATE TABLE TB_DEPARTMENT (
	DEPT_NO NUMBER PRIMARY KEY,
	DEPT_NAME VARCHAR2(30),
	DEPT_PHONE VARCHAR2(20),
	DEPT_OFFICE VARCHAR2(20),
	DEPT_CLASS VARCHAR2(30) NOT NULL,
	DEPT_PROF_NO NUMBER CONSTRAINT DEPT_PROF_NO_FK REFERENCES TB_PROFESSOR

)


-- 동아리
CREATE TABLE CLUB(
CLUB_NO NUMBER PRIMARY KEY,
CLUB_NAME VARCHAR2(30),
CLUB_PEOPLE_CNT NUMBER,
CLUB_STD_PRESIDENT NUMBER CONSTRAINT CLUB_STD_PRESIDEN_FK REFERENCES TB_STUDENT,
CLUB_PROF_NO NUMBER CONSTRAINT CLUB_PROF_NO_FK REFERENCES TB_PROFESSOR,
CLUBROOM VARCHAR2(20)
);


-- 수강내역
학생번호
강좌번호
교수번호

출석점수
중간고사 점수
기말고사 점수
기타점수
총점
평점

-- 등록금 납부 내역
학생번호
등록금 납보 연도
등록금 납부 학기
등록금총액
마지막 납부일자
