SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;

-- 1번
SELECT department_name "학과 명", category "계열" FROM TB_DEPARTMENT;

-- 2번 학과별 정원
SELECT department_name||'학과의 정원은 ' || capacity||'명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3번
SELECT student_name
FROM TB_STUDENT
WHERE DEPARTMENT_NO ='001'
AND absence_yn = 'Y'
AND STUDENT_SSN LIKE '_______2%';

-- 4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO ='A513079'
OR STUDENT_NO ='A513090'
OR STUDENT_NO ='A513091'
OR STUDENT_NO ='A513110'
OR STUDENT_NO ='A513119'
ORDER BY STUDENT_NAME DESC;

-- 5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;


-- 6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


-- 7번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;


-- 8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


-- 9번
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;


-- 10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE BETWEEN '2002-01-01' AND '2002-12-31'
AND ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '%전주%';